import {AxiosResponse} from "axios";

import {AuthModel} from "./AuthModel";

export interface ApiErrorDetails {
    authModel?: AuthModel,
    axiosResponse?: AxiosResponse,
    requestModel?: unknown//{}
}

class ApiError {

    errorMessage: string;
    details: ApiErrorDetails;

    constructor(errorMessage: string, details: ApiErrorDetails) {
        this.errorMessage = errorMessage;
        this.details = details;
    }

    getUserError(): string {
        if (this.errorMessage === "502" || "400") {
            return "Ups. Da ist etwas schief gelaufen. ü§≠ \nWir beheben den Fehler so schnell wie m√∂glich."
        } else if (this.errorMessage === "Network request failed") {
            return "Der Service konnte nicht erreicht werden. Pr√ºfe deine Internetverbindung und versuche es erneut."
        } else {
            return "Es ist ein unbekannter Fehler aufgetreten";
        }
    }
}

export default ApiError